linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/convidera/devops-parallel-runner

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
